### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by gummipunkt** [kghorvath/atmigration#3]
```
% ./atmigration.sh
This script will assist in migrating an AT Protocol account between two personal data servers (PDS). Note: This script DOES NOT PERFORM ANY ERROR CHECKING. You are responsible for confirming that all steps have proceeded correctly. I take absolutely no responsibility for anything that occurs as a result of this script.
If you understand and Wish to proceed, type I UNDERSTAND: I UNDERSTAND
Please enter the originating PDS you want to migrate from: bsky.social
Please enter the credentials for the account you want to migrate.
Handle: @handle.bsky.social
Password (will not echo): Fetching tokens and user information
Your DID is did:plc:rxbuythw6hplq********
Please enter the target PDS you want to migrate to: domain.dev
Fetching service auth...
Please enter the credentials for the new account you would like to create on the target PDS
Handle: @handle.domain.tld
Password (will not echo): *****
Email: handle@domain.tld
Invite Code: domain-tld-****-oeizw
Account successfully created!

Current Status for @handle.domain.tld
--------------------------------------------------------------
Activation Status: null
Valid DID Status: null
Blobs to import: null
Blobs imported: null
Exporting repo from old PDS to ~/temp/
Importing repo to new PDS
{"error":"InternalServerError","message":"Internal Server Error"}Exporting preferences from old PDS
Importing preferences to new PDS
{"error":"InternalServerError","message":"Internal Server Error"}Checking existing blobs
```

cli account create with pdsadmin works well

```
:/pds# pdsadmin account create handle@domain.tld handle.domain.tld

Account created successfully!
-----------------------------
Handle   : handle.domain.tld
DID      : did:plc:o5zcao*****************
Password : passwordexample
-----------------------------
Save this password, it will not be displayed again.

```

**Comment by kghorvath** [comment]
Can you try the version in the debug branch? I added a pause after account creation where it will echo the result of the request to the destination server. Let me know what it says.

**Comment by gummipunkt** [comment]
> Can you try the version in the debug branch? I added a pause after account creation where it will echo the result of the request to the destination server. Let me know what it says.

{"error":"AlreadyExists","message":"Repo already exists"}

/temp folder is empty

thank you

**Comment by kghorvath** [comment]
I wonder if this is because it's trying to create an account that already exists on the destination server. Have you tried it with a new account? Unfortunately I haven't coded in any ability to handle a pre-existing account yet.

**Comment by gummipunkt** [comment]
> I wonder if this is because it's trying to create an account that already exists on the destination server. Have you tried it with a new account? Unfortunately I haven't coded in any ability to handle a pre-existing account yet.

no, the pds is empty and there are no accounts, i've checked it. I've created now a account with pdsadmin create and deleted it afterwards. it worked as expected.

**Comment by gummipunkt** [comment]
Ok, removed and reinstalled the pds, run your script again and now everything works as expected. thank you!
